
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Usuario
 */
public class FormCrearGrupoAlimento extends javax.swing.JFrame {

    /**
     * Creates new form FormCrearGrupoAlimento
     */
    public FormCrearGrupoAlimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Codigo = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        txtCodigoGrupoAlimento = new javax.swing.JTextField();
        txtNombreGrupoAlimento = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescripcionNuevoGrupo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Nuevo Grupo Alimento");
        setResizable(false);

        Codigo.setText("Código:");

        Nombre.setText("Nombre:");

        Descripcion.setText("Descripción:");

        txtCodigoGrupoAlimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoGrupoAlimentoKeyTyped(evt);
            }
        });

        txtNombreGrupoAlimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreGrupoAlimentoKeyTyped(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtAreaDescripcionNuevoGrupo.setColumns(20);
        txtAreaDescripcionNuevoGrupo.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescripcionNuevoGrupo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Codigo)
                    .addComponent(Nombre)
                    .addComponent(Descripcion))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(txtNombreGrupoAlimento)
                    .addComponent(txtCodigoGrupoAlimento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 112, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigo)
                    .addComponent(txtCodigoGrupoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(txtNombreGrupoAlimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Descripcion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if (Utilitaria.validarCadenaVacia(this.txtNombreGrupoAlimento.getText()) && Utilitaria.validarCadenaVacia(this.txtCodigoGrupoAlimento.getText())
                && Utilitaria.validarCadenaVacia(this.txtAreaDescripcionNuevoGrupo.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar el:\n * Código\n"
                    + " * Nombre\n * Descripción\n ", "Atención");
            this.txtCodigoGrupoAlimento.requestFocus();
        } else if (Utilitaria.validarCadenaVacia(this.txtCodigoGrupoAlimento.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar el código del grupo de alimento", "Atención");
            this.txtCodigoGrupoAlimento.requestFocus();

        } else if (Utilitaria.validarCadenaVacia(this.txtNombreGrupoAlimento.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar el nombre del grupo de alimento", "Atención");
            this.txtNombreGrupoAlimento.requestFocus();

        } else if (Utilitaria.validarCadenaVacia(this.txtAreaDescripcionNuevoGrupo.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar la descripción del grupo de alimento", "Atención");
            this.txtAreaDescripcionNuevoGrupo.requestFocus();
        } else {

            GrupoAlimento p = new GrupoAlimento(this.txtCodigoGrupoAlimento.getText(),
                    this.txtNombreGrupoAlimento.getText(),
                    this.txtAreaDescripcionNuevoGrupo.getText());
            Test.grupo.agregarGrupoAlimento(p);

            Utilitaria.imprimirEnVentanaInformativa("Un (1) grupo grabado", "Validación Grupo Alimento");
        }

        this.txtCodigoGrupoAlimento.setText("");
        this.txtNombreGrupoAlimento.setText("");
        this.txtAreaDescripcionNuevoGrupo.setText("");
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtCodigoGrupoAlimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoGrupoAlimentoKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoGrupoAlimentoKeyTyped

    private void txtNombreGrupoAlimentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreGrupoAlimentoKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreGrupoAlimentoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCrearGrupoAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCrearGrupoAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCrearGrupoAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCrearGrupoAlimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCrearGrupoAlimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaDescripcionNuevoGrupo;
    private javax.swing.JTextField txtCodigoGrupoAlimento;
    private javax.swing.JTextField txtNombreGrupoAlimento;
    // End of variables declaration//GEN-END:variables
}
