
import java.awt.event.KeyEvent;
import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrador
 */
public class FormSedeDeseos extends javax.swing.JFrame {

    public FormSedeDeseos() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPaneIngredientes = new javax.swing.JPanel();
        btnIngredientes1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaIngredientesSedePrincipal = new javax.swing.JTextArea();
        btnBuscarIngredienteSedeDeseos = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtBuscarIngredienteSedeDeseos = new javax.swing.JTextField();
        btnCancelarBusqueda = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPaneGrupoAlimentos = new javax.swing.JPanel();
        btnGrupoAlimentos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtBuscarGrupoAlimentoSedeDeseos = new javax.swing.JTextField();
        btnBuscarGrupoAlimentoSedeDeseos1 = new javax.swing.JButton();
        btnCancelarBusqueda1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaGruposAlimentosSedeDeseos = new javax.swing.JTextArea();
        btnVerIngredientesGrupo = new javax.swing.JButton();
        jPanePlatos = new javax.swing.JPanel();
        btnInventarioPlatos = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtBuscarPlatoSedeDeseos = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaPlatosSedeDeseos = new javax.swing.JTextArea();
        btnBuscarPlatoSedeDeseos = new javax.swing.JButton();
        btnCancelarBusquedaPlato = new javax.swing.JButton();
        btnVerIngredientePlato = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbuttonSedeEstadoActiva = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnSalirSedeDeseos = new javax.swing.JButton();
        btnEntradaIngrediente = new javax.swing.JButton();
        btnSalidaIngrediente = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuGuardarComo = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deliricuras S.A.");
        setBackground(new java.awt.Color(153, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPaneIngredientes.setBackground(new java.awt.Color(255, 255, 255));

        btnIngredientes1.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        btnIngredientes1.setText("Inventario Ingredientes");
        btnIngredientes1.setMaximumSize(new java.awt.Dimension(101, 27));
        btnIngredientes1.setMinimumSize(new java.awt.Dimension(101, 27));
        btnIngredientes1.setName(""); // NOI18N
        btnIngredientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngredientes1ActionPerformed(evt);
            }
        });

        txtAreaIngredientesSedePrincipal.setEditable(false);
        txtAreaIngredientesSedePrincipal.setColumns(20);
        txtAreaIngredientesSedePrincipal.setRows(5);
        txtAreaIngredientesSedePrincipal.setText("\n");
        jScrollPane2.setViewportView(txtAreaIngredientesSedePrincipal);

        btnBuscarIngredienteSedeDeseos.setText("Buscar");
        btnBuscarIngredienteSedeDeseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIngredienteSedeDeseosActionPerformed(evt);
            }
        });

        jLabel16.setText("Buscar Ingrediente");

        btnCancelarBusqueda.setText("Cancelar");
        btnCancelarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusquedaActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("(Por Código)");

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("por ejemplo: 01,02,03...etc");

        javax.swing.GroupLayout jPaneIngredientesLayout = new javax.swing.GroupLayout(jPaneIngredientes);
        jPaneIngredientes.setLayout(jPaneIngredientesLayout);
        jPaneIngredientesLayout.setHorizontalGroup(
            jPaneIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneIngredientesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPaneIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneIngredientesLayout.createSequentialGroup()
                        .addGroup(jPaneIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPaneIngredientesLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 113, Short.MAX_VALUE))
                            .addGroup(jPaneIngredientesLayout.createSequentialGroup()
                                .addComponent(txtBuscarIngredienteSedeDeseos)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarIngredienteSedeDeseos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarBusqueda)
                        .addGap(118, 118, 118))
                    .addGroup(jPaneIngredientesLayout.createSequentialGroup()
                        .addGroup(jPaneIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIngredientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPaneIngredientesLayout.setVerticalGroup(
            jPaneIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneIngredientesLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnIngredientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPaneIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(7, 7, 7)
                .addGroup(jPaneIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarIngredienteSedeDeseos)
                    .addComponent(txtBuscarIngredienteSedeDeseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarBusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ingredientes", jPaneIngredientes);

        btnGrupoAlimentos.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        btnGrupoAlimentos.setText("Grupos de Alimentos");
        btnGrupoAlimentos.setMaximumSize(new java.awt.Dimension(101, 27));
        btnGrupoAlimentos.setMinimumSize(new java.awt.Dimension(101, 27));
        btnGrupoAlimentos.setName(""); // NOI18N
        btnGrupoAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoAlimentosActionPerformed(evt);
            }
        });

        jLabel23.setText("Buscar Grupo de Alimento");

        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("(Por Código)");

        btnBuscarGrupoAlimentoSedeDeseos1.setText("Buscar");
        btnBuscarGrupoAlimentoSedeDeseos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGrupoAlimentoSedeDeseos1ActionPerformed(evt);
            }
        });

        btnCancelarBusqueda1.setText("Cancelar");
        btnCancelarBusqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusqueda1ActionPerformed(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("por ejemplo: 1431,1432,1433...etc");

        txtAreaGruposAlimentosSedeDeseos.setEditable(false);
        txtAreaGruposAlimentosSedeDeseos.setColumns(20);
        txtAreaGruposAlimentosSedeDeseos.setRows(5);
        txtAreaGruposAlimentosSedeDeseos.setText("\n");
        jScrollPane4.setViewportView(txtAreaGruposAlimentosSedeDeseos);

        btnVerIngredientesGrupo.setText("Ver Ingredientes");
        btnVerIngredientesGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerIngredientesGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneGrupoAlimentosLayout = new javax.swing.GroupLayout(jPaneGrupoAlimentos);
        jPaneGrupoAlimentos.setLayout(jPaneGrupoAlimentosLayout);
        jPaneGrupoAlimentosLayout.setHorizontalGroup(
            jPaneGrupoAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneGrupoAlimentosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPaneGrupoAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneGrupoAlimentosLayout.createSequentialGroup()
                        .addComponent(btnGrupoAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneGrupoAlimentosLayout.createSequentialGroup()
                        .addGroup(jPaneGrupoAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPaneGrupoAlimentosLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnVerIngredientesGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPaneGrupoAlimentosLayout.createSequentialGroup()
                                .addGroup(jPaneGrupoAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPaneGrupoAlimentosLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 81, Short.MAX_VALUE))
                                    .addGroup(jPaneGrupoAlimentosLayout.createSequentialGroup()
                                        .addComponent(txtBuscarGrupoAlimentoSedeDeseos)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarGrupoAlimentoSedeDeseos1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarBusqueda1)))
                        .addGap(116, 116, 116)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPaneGrupoAlimentosLayout.setVerticalGroup(
            jPaneGrupoAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneGrupoAlimentosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnGrupoAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPaneGrupoAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(7, 7, 7)
                .addGroup(jPaneGrupoAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarGrupoAlimentoSedeDeseos1)
                    .addComponent(txtBuscarGrupoAlimentoSedeDeseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarBusqueda1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneGrupoAlimentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(btnVerIngredientesGrupo))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPaneGrupoAlimentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Grupos de Alimentos", jPaneGrupoAlimentos);

        btnInventarioPlatos.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        btnInventarioPlatos.setText("Inventario Platos");
        btnInventarioPlatos.setMaximumSize(new java.awt.Dimension(101, 27));
        btnInventarioPlatos.setMinimumSize(new java.awt.Dimension(101, 27));
        btnInventarioPlatos.setName(""); // NOI18N
        btnInventarioPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioPlatosActionPerformed(evt);
            }
        });

        jLabel19.setText("Buscar Plato");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("(Por Código)");

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("por ejemplo: 01,02,03...etc");

        txtAreaPlatosSedeDeseos.setEditable(false);
        txtAreaPlatosSedeDeseos.setColumns(20);
        txtAreaPlatosSedeDeseos.setRows(5);
        txtAreaPlatosSedeDeseos.setText("\n");
        jScrollPane3.setViewportView(txtAreaPlatosSedeDeseos);

        btnBuscarPlatoSedeDeseos.setText("Buscar");
        btnBuscarPlatoSedeDeseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlatoSedeDeseosActionPerformed(evt);
            }
        });

        btnCancelarBusquedaPlato.setText("Cancelar");
        btnCancelarBusquedaPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusquedaPlatoActionPerformed(evt);
            }
        });

        btnVerIngredientePlato.setText("Ver Ingredientes");

        javax.swing.GroupLayout jPanePlatosLayout = new javax.swing.GroupLayout(jPanePlatos);
        jPanePlatos.setLayout(jPanePlatosLayout);
        jPanePlatosLayout.setHorizontalGroup(
            jPanePlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanePlatosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanePlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanePlatosLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanePlatosLayout.createSequentialGroup()
                        .addGroup(jPanePlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanePlatosLayout.createSequentialGroup()
                                .addComponent(txtBuscarPlatoSedeDeseos)
                                .addGap(18, 18, 18))
                            .addGroup(jPanePlatosLayout.createSequentialGroup()
                                .addGroup(jPanePlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnInventarioPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)))
                        .addGroup(jPanePlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanePlatosLayout.createSequentialGroup()
                                .addComponent(btnBuscarPlatoSedeDeseos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelarBusquedaPlato))
                            .addComponent(btnVerIngredientePlato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(109, 109, 109)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanePlatosLayout.setVerticalGroup(
            jPanePlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanePlatosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnInventarioPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanePlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addGap(7, 7, 7)
                .addGroup(jPanePlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarPlatoSedeDeseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPlatoSedeDeseos)
                    .addComponent(btnCancelarBusquedaPlato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanePlatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(btnVerIngredientePlato))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanePlatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Platos", jPanePlatos);

        jLabel2.setText("Tipo Transacción:");

        jLabel3.setText("Fecha:");

        jLabel5.setText("Estado Sede:");

        jbuttonSedeEstadoActiva.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jbuttonSedeEstadoActiva.setSelected(true);
        jbuttonSedeEstadoActiva.setText("Activa");
        jbuttonSedeEstadoActiva.setEnabled(false);

        jCheckBox4.setText("Inactiva");
        jCheckBox4.setEnabled(false);

        jLabel6.setText("Sede:");

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Deseos");

        jLabel8.setText("Código:");

        jLabel9.setText("Dirección:");

        jLabel10.setText("Nombre Admin:");

        jLabel11.setText("Telefono:");

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("214607");

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Carlos Amparo ");

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("4956285");

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Cra 3N #12-35");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo15an_os_opt.jpg"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSalirSedeDeseos.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        btnSalirSedeDeseos.setText("SALIR");
        btnSalirSedeDeseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirSedeDeseosActionPerformed(evt);
            }
        });

        btnEntradaIngrediente.setText("Entrada");
        btnEntradaIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaIngredienteActionPerformed(evt);
            }
        });

        btnSalidaIngrediente.setText("Salida");
        btnSalidaIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaIngredienteActionPerformed(evt);
            }
        });

        jLabelFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu2.setText("inicio");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuGuardar);

        jMenuGuardarComo.setText("Guardar como...");

        jMenuItem2.setText(".java");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuGuardarComo.add(jMenuItem2);

        jMenuItem3.setText(".exe");
        jMenuGuardarComo.add(jMenuItem3);

        jMenu2.add(jMenuGuardarComo);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jbuttonSedeEstadoActiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntradaIngrediente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalidaIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(27, 27, 27))
            .addComponent(btnSalirSedeDeseos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jbuttonSedeEstadoActiva)
                            .addComponent(jCheckBox4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEntradaIngrediente)
                                .addComponent(btnSalidaIngrediente)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalirSedeDeseos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(958, 626));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngredientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientes1ActionPerformed
        FormIngrediente x = new FormIngrediente();

        x.setVisible(true);

    }//GEN-LAST:event_btnIngredientes1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        JOptionPane.showMessageDialog(null, "Guardado con Éxito");
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void btnBuscarIngredienteSedeDeseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIngredienteSedeDeseosActionPerformed

        String cad = (this.txtBuscarIngredienteSedeDeseos.getText());
        int pos = Test.ai.buscarIngredienteXCodigo(cad);
        if (pos == -1) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar un código valido", "Atención");

        } else {

            Utilitaria.imprimirEnVentanaInformativa(" Un (1) ingrediente encontrado", "Atención");

            txtAreaIngredientesSedePrincipal.append("CÓDIGO: \t\t" + Test.ai.arr_i[ pos].codigo + "\nNOMBRE: \t\t" + Test.ai.arr_i[ pos].getNombre()
                    + "\nDESCRIPCIÓN: \t" + Test.ai.arr_i[ pos].descripcion + " \nUNIDAD DE MEDIDA: \t" + Test.ai.arr_i[ pos].unidadMedida
                    + "\nCOSTO: \t\t" + Test.ai.arr_i[ pos].getCosto() + " pesos" + "\nSTOCK: \t\t" + Test.ai.arr_i[ pos].stock
                    + " en existencia" + " \nGRUPO ALIMENTO: \t" + Test.ai.arr_i[ pos].getGrupoAlimento());

        }

        this.txtBuscarIngredienteSedeDeseos.setText("");
    }//GEN-LAST:event_btnBuscarIngredienteSedeDeseosActionPerformed

    private void btnCancelarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusquedaActionPerformed
        txtAreaIngredientesSedePrincipal.setText("");
        txtBuscarIngredienteSedeDeseos.setText("");
    }//GEN-LAST:event_btnCancelarBusquedaActionPerformed

    private void btnInventarioPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioPlatosActionPerformed

        FormPlato plato1 = new FormPlato();
        plato1.setVisible(true);


    }//GEN-LAST:event_btnInventarioPlatosActionPerformed

    private void btnBuscarPlatoSedeDeseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlatoSedeDeseosActionPerformed
        String cad = (this.txtBuscarPlatoSedeDeseos.getText());
        int pos = Test.menu.buscarPlatoXCodigo(cad);
        if (pos == -1) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar un código valido", "Atención");

        }


    }//GEN-LAST:event_btnBuscarPlatoSedeDeseosActionPerformed

    private void btnCancelarBusquedaPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusquedaPlatoActionPerformed
        txtAreaPlatosSedeDeseos.setText("");
        txtBuscarPlatoSedeDeseos.setText("");
    }//GEN-LAST:event_btnCancelarBusquedaPlatoActionPerformed

    private void btnSalirSedeDeseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirSedeDeseosActionPerformed
        
        FormResumenConsolidado resu = new FormResumenConsolidado();    
        
        FormResumenConsolidado.txtAreaResumenConsolidado.append("Nombre del Comerciante:\t"+ FormRegistro.txtNomComerciante.getText());
        resu.setVisible(true);
       
    }//GEN-LAST:event_btnSalirSedeDeseosActionPerformed

    private void btnEntradaIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaIngredienteActionPerformed

        FormAgregarIngrediente nonas = new FormAgregarIngrediente();
        nonas.setVisible(true);
    }//GEN-LAST:event_btnEntradaIngredienteActionPerformed

    private void btnSalidaIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaIngredienteActionPerformed
        FormSacarIngrediente sisasnene = new FormSacarIngrediente();
        sisasnene.setVisible(true);
    }//GEN-LAST:event_btnSalidaIngredienteActionPerformed

    private void btnCancelarBusqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusqueda1ActionPerformed
        this.txtBuscarGrupoAlimentoSedeDeseos.setText("");
        this.txtAreaGruposAlimentosSedeDeseos.setText("");
    }//GEN-LAST:event_btnCancelarBusqueda1ActionPerformed

    private void btnBuscarGrupoAlimentoSedeDeseos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGrupoAlimentoSedeDeseos1ActionPerformed
        String cad = this.txtBuscarGrupoAlimentoSedeDeseos.getText();
        int pos = Test.grupo.buscarIngredienteXCodigo(cad);
        if (pos == -1) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar un código valido", "Atención");

        } else {

            Utilitaria.imprimirEnVentanaInformativa(" Un (1) grupo encontrado", "Atención");
            txtAreaGruposAlimentosSedeDeseos.append("CÓDIGO: \t\t" + Test.grupo.arr_i[pos].codigo +
                                                    "\nNOMBRE: \t\t" + Test.grupo.arr_i[pos].nombreGrupoAlimento +
                                                    "\nDESCRIPCIÓN: \t" + Test.grupo.arr_i[pos].descripcion);
        }
        
    }//GEN-LAST:event_btnBuscarGrupoAlimentoSedeDeseos1ActionPerformed

    private void btnGrupoAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoAlimentosActionPerformed
       FormGrupoAlimentos ricos = new FormGrupoAlimentos();
       ricos.setVisible(true);
    }//GEN-LAST:event_btnGrupoAlimentosActionPerformed

    private void btnVerIngredientesGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerIngredientesGrupoActionPerformed
        FormVerIngredienteGrupoAlimento hello = new FormVerIngredienteGrupoAlimento();
        hello.setVisible(true);
    }//GEN-LAST:event_btnVerIngredientesGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSedeDeseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSedeDeseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSedeDeseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSedeDeseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSedeDeseos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarGrupoAlimentoSedeDeseos1;
    private javax.swing.JButton btnBuscarIngredienteSedeDeseos;
    private javax.swing.JButton btnBuscarPlatoSedeDeseos;
    private javax.swing.JButton btnCancelarBusqueda;
    private javax.swing.JButton btnCancelarBusqueda1;
    private javax.swing.JButton btnCancelarBusquedaPlato;
    private javax.swing.JButton btnEntradaIngrediente;
    private javax.swing.JButton btnGrupoAlimentos;
    private javax.swing.JButton btnIngredientes1;
    private javax.swing.JButton btnInventarioPlatos;
    private javax.swing.JButton btnSalidaIngrediente;
    public static javax.swing.JButton btnSalirSedeDeseos;
    private javax.swing.JButton btnVerIngredientePlato;
    private javax.swing.JButton btnVerIngredientesGrupo;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelFecha;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenu jMenuGuardarComo;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JPanel jPaneGrupoAlimentos;
    public javax.swing.JPanel jPaneIngredientes;
    private javax.swing.JPanel jPanePlatos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jbuttonSedeEstadoActiva;
    public static javax.swing.JTextArea txtAreaGruposAlimentosSedeDeseos;
    public static javax.swing.JTextArea txtAreaIngredientesSedePrincipal;
    public static javax.swing.JTextArea txtAreaPlatosSedeDeseos;
    public static javax.swing.JTextField txtBuscarGrupoAlimentoSedeDeseos;
    private javax.swing.JTextField txtBuscarIngredienteSedeDeseos;
    private javax.swing.JTextField txtBuscarPlatoSedeDeseos;
    // End of variables declaration//GEN-END:variables
}
