/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrador
 */
public class FormNuevaSede extends javax.swing.JFrame {

   
    public FormNuevaSede() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnIngredientes1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaIngredientesNuevaSede = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtBuscarIngredienteSedeDeseos = new javax.swing.JTextField();
        btnBuscarIngredienteSedeDeseos = new javax.swing.JButton();
        btnCancelarBusqueda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnGrupoAlimentos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtBuscarGrupoAlimentoSedeDeseos1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnBuscarGrupoAlimentoSedeDeseos1 = new javax.swing.JButton();
        btnCancelarBusqueda1 = new javax.swing.JButton();
        btnCrearNuevoGrupo = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaGruposAlimentosSedeDeseos = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtBuscarPlatoSedeDeseos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnBuscarPlatoSedeDeseos = new javax.swing.JButton();
        btnCancelarBusquedaPlato = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnInventarioPlatos = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaPlatosNuevaSede = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckNuevaSedeEstadoActiva = new javax.swing.JCheckBox();
        jCheckNuevaSedeEstadoInactiva = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabelNombreSede = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        try {
            jLabelCodigoNuevaSede =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "FormNuevaSede_jLabelCodigoNuevaSede");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jLabel9 = new javax.swing.JLabel();
        jLabelDireccionNuevaSede = new javax.swing.JLabel();
        jLabelTelefonoSede = new javax.swing.JLabel();
        jLabelNomAdmSede = new javax.swing.JLabel();
        jLabelNomAdmNuevaSede = new javax.swing.JLabel();
        jLabelTelefonoNuevaSede = new javax.swing.JLabel();
        btnEntradaIngrediente = new javax.swing.JButton();
        btnSalidaIngrediente = new javax.swing.JButton();
        btnVerResumen = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Deliricuras S.A.");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSalir.setText("SALIR");
        btnSalir.setName(""); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnIngredientes1.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        btnIngredientes1.setText("Inventario Ingredientes");
        btnIngredientes1.setMaximumSize(new java.awt.Dimension(101, 27));
        btnIngredientes1.setMinimumSize(new java.awt.Dimension(101, 27));
        btnIngredientes1.setName(""); // NOI18N
        btnIngredientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngredientes1ActionPerformed(evt);
            }
        });

        txtAreaIngredientesNuevaSede.setColumns(20);
        txtAreaIngredientesNuevaSede.setRows(5);
        jScrollPane2.setViewportView(txtAreaIngredientesNuevaSede);

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("por ejemplo: 01,02,03...etc");

        jLabel16.setText("Buscar Ingrediente");

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("(Por Código)");

        btnBuscarIngredienteSedeDeseos.setText("Buscar");
        btnBuscarIngredienteSedeDeseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIngredienteSedeDeseosActionPerformed(evt);
            }
        });

        btnCancelarBusqueda.setText("Cancelar");
        btnCancelarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngredientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscarIngredienteSedeDeseos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnBuscarIngredienteSedeDeseos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarBusqueda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnIngredientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarIngredienteSedeDeseos)
                    .addComponent(txtBuscarIngredienteSedeDeseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarBusqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingredientes", jPanel1);

        btnGrupoAlimentos.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        btnGrupoAlimentos.setText("Grupos de Alimentos");
        btnGrupoAlimentos.setMaximumSize(new java.awt.Dimension(101, 27));
        btnGrupoAlimentos.setMinimumSize(new java.awt.Dimension(101, 27));
        btnGrupoAlimentos.setName(""); // NOI18N
        btnGrupoAlimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoAlimentosActionPerformed(evt);
            }
        });

        jLabel23.setText("Buscar Grupo de Alimento");

        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("(Por Código)");

        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("por ejemplo: 01,02,03...etc");

        jButton1.setText("Ver Ingredientes");

        btnBuscarGrupoAlimentoSedeDeseos1.setText("Buscar");
        btnBuscarGrupoAlimentoSedeDeseos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGrupoAlimentoSedeDeseos1ActionPerformed(evt);
            }
        });

        btnCancelarBusqueda1.setText("Cancelar");
        btnCancelarBusqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusqueda1ActionPerformed(evt);
            }
        });

        btnCrearNuevoGrupo.setText("Crear Nuevo Grupo");
        btnCrearNuevoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearNuevoGrupoActionPerformed(evt);
            }
        });

        txtAreaGruposAlimentosSedeDeseos.setEditable(false);
        txtAreaGruposAlimentosSedeDeseos.setColumns(20);
        txtAreaGruposAlimentosSedeDeseos.setRows(5);
        txtAreaGruposAlimentosSedeDeseos.setText("\n");
        jScrollPane4.setViewportView(txtAreaGruposAlimentosSedeDeseos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnGrupoAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnCrearNuevoGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(73, 73, 73)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtBuscarGrupoAlimentoSedeDeseos1)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnBuscarGrupoAlimentoSedeDeseos1)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancelarBusqueda1))))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrupoAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearNuevoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarGrupoAlimentoSedeDeseos1)
                    .addComponent(txtBuscarGrupoAlimentoSedeDeseos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarBusqueda1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jButton1))
                .addGap(61, 61, 61))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Grupos de Alimentos", jPanel2);

        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("por ejemplo: 01,02,03...etc");

        jLabel19.setText("Buscar Plato");

        btnBuscarPlatoSedeDeseos.setText("Buscar");
        btnBuscarPlatoSedeDeseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlatoSedeDeseosActionPerformed(evt);
            }
        });

        btnCancelarBusquedaPlato.setText("Cancelar");
        btnCancelarBusquedaPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarBusquedaPlatoActionPerformed(evt);
            }
        });

        jButton2.setText("Ver Ingredientes");

        btnInventarioPlatos.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        btnInventarioPlatos.setText("Inventario Platos");
        btnInventarioPlatos.setMaximumSize(new java.awt.Dimension(101, 27));
        btnInventarioPlatos.setMinimumSize(new java.awt.Dimension(101, 27));
        btnInventarioPlatos.setName(""); // NOI18N
        btnInventarioPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioPlatosActionPerformed(evt);
            }
        });

        txtAreaPlatosNuevaSede.setColumns(20);
        txtAreaPlatosNuevaSede.setRows(5);
        jScrollPane3.setViewportView(txtAreaPlatosNuevaSede);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInventarioPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtBuscarPlatoSedeDeseos, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnBuscarPlatoSedeDeseos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarBusquedaPlato))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(btnInventarioPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel19)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarPlatoSedeDeseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPlatoSedeDeseos)
                    .addComponent(btnCancelarBusquedaPlato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jButton2))
                .addGap(56, 56, 56))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Platos", jPanel3);

        jLabel2.setText("Tipo Transacción:");

        jLabel3.setText("Fecha:");

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("(dd:mm:aaaa)");

        jLabel5.setText("Estado Sede:");

        jCheckNuevaSedeEstadoActiva.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jCheckNuevaSedeEstadoActiva.setText("Activa");
        jCheckNuevaSedeEstadoActiva.setEnabled(false);

        jCheckNuevaSedeEstadoInactiva.setText("Inactiva");
        jCheckNuevaSedeEstadoInactiva.setEnabled(false);

        jLabel6.setText("Sede:");

        jLabelNombreSede.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNombreSede.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNombreSede.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel8.setText("Código:");

        jLabel9.setText("Dirección:");

        jLabelDireccionNuevaSede.setForeground(new java.awt.Color(102, 102, 102));
        jLabelDireccionNuevaSede.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelDireccionNuevaSede.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabelTelefonoSede.setText("Telefono:");

        jLabelNomAdmSede.setText("Nombre Admin:");

        jLabelNomAdmNuevaSede.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNomAdmNuevaSede.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNomAdmNuevaSede.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabelTelefonoNuevaSede.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTelefonoNuevaSede.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTelefonoNuevaSede.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnEntradaIngrediente.setText("Entrada");
        btnEntradaIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaIngredienteActionPerformed(evt);
            }
        });

        btnSalidaIngrediente.setText("Salida");
        btnSalidaIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaIngredienteActionPerformed(evt);
            }
        });

        btnVerResumen.setText("Ver Resumen");
        btnVerResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerResumenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckNuevaSedeEstadoActiva)
                        .addGap(2, 2, 2)
                        .addComponent(jCheckNuevaSedeEstadoInactiva)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabelCodigoNuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabelDireccionNuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntradaIngrediente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalidaIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomAdmSede)
                            .addComponent(jLabelNomAdmNuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefonoSede)
                            .addComponent(jLabelTelefonoNuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130)
                        .addComponent(btnVerResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))))
            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabelNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addComponent(jCheckNuevaSedeEstadoActiva)
                    .addComponent(jCheckNuevaSedeEstadoInactiva)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2)
                        .addComponent(jLabelCodigoNuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelDireccionNuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEntradaIngrediente)
                            .addComponent(btnSalidaIngrediente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelNomAdmSede)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNomAdmNuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelTelefonoSede)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelTelefonoNuevaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnVerResumen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4)))
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(200, 200, 920, 604);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Imprime cuadro de mensaje
        Utilitaria.imprimirEnVentanaInformativa("Gracias por utilizar nuestros servicios.","Atención");
        // cierra la ventana actual
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngredientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngredientes1ActionPerformed
        FormIngrediente x = new FormIngrediente();
        
        x.setVisible(true);
        
    }//GEN-LAST:event_btnIngredientes1ActionPerformed

    private void btnBuscarIngredienteSedeDeseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIngredienteSedeDeseosActionPerformed

        String cad = (this.txtBuscarIngredienteSedeDeseos.getText());
        int pos = Test.ai.buscarIngredienteXCodigo(cad);
        if (pos == -1){
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar un código valido", "Atención");

        }

        else
        {

            Utilitaria.imprimirEnVentanaInformativa(" Un (1) ingrediente encontrado", "Atención");

            txtAreaIngredientesNuevaSede.append("CÓDIGO: \t\t" + Test.ai.arr_i[ pos ].codigo + "\nNOMBRE: \t\t" + Test.ai.arr_i[ pos ].getNombre() +
                "\nDESCRIPCIÓN: \t" + Test.ai.arr_i[ pos ].descripcion + " \nUNIDAD DE MEDIDA: \t"+ Test.ai.arr_i[ pos ].unidadMedida +
                "\nCOSTO: \t\t" + Test.ai.arr_i[ pos ].getCosto() +" pesos"+ "\nSTOCK: \t\t" + Test.ai.arr_i[ pos ].stock +
                " en existencia" +" \nGRUPO ALIMENTO: \t"+Test.ai.arr_i[ pos ].getGrupoAlimento());

        }

        this.txtBuscarIngredienteSedeDeseos.setText("");
    }//GEN-LAST:event_btnBuscarIngredienteSedeDeseosActionPerformed

    private void btnCancelarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusquedaActionPerformed
        txtAreaIngredientesNuevaSede.setText("");
        txtBuscarIngredienteSedeDeseos.setText("");
    }//GEN-LAST:event_btnCancelarBusquedaActionPerformed

    private void btnBuscarPlatoSedeDeseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlatoSedeDeseosActionPerformed
        String cad = (this.txtBuscarPlatoSedeDeseos.getText());
        int pos = Test.menu.buscarPlatoXCodigo(cad);
        if (pos == -1){
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar un código valido", "Atención");

        }

    }//GEN-LAST:event_btnBuscarPlatoSedeDeseosActionPerformed

    private void btnCancelarBusquedaPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusquedaPlatoActionPerformed
        txtAreaPlatosNuevaSede.setText("");
        txtBuscarPlatoSedeDeseos.setText("");
    }//GEN-LAST:event_btnCancelarBusquedaPlatoActionPerformed

    private void btnInventarioPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioPlatosActionPerformed

        FormPlato plato1 = new FormPlato();
        plato1.setVisible(true);

    }//GEN-LAST:event_btnInventarioPlatosActionPerformed

    private void btnVerResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerResumenActionPerformed
        FormResumenConsolidado sisas = new FormResumenConsolidado();
        sisas.setVisible(true);
    }//GEN-LAST:event_btnVerResumenActionPerformed

    private void btnEntradaIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaIngredienteActionPerformed
       FormAgregarIngrediente peres = new FormAgregarIngrediente();
       peres.setVisible(true);
    }//GEN-LAST:event_btnEntradaIngredienteActionPerformed

    private void btnSalidaIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaIngredienteActionPerformed
        FormSacarIngrediente sisasnene = new FormSacarIngrediente();
        sisasnene.setVisible(true);
    }//GEN-LAST:event_btnSalidaIngredienteActionPerformed

    private void btnGrupoAlimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoAlimentosActionPerformed
        FormGrupoAlimentos ricos = new FormGrupoAlimentos();
        ricos.setVisible(true);
    }//GEN-LAST:event_btnGrupoAlimentosActionPerformed

    private void btnBuscarGrupoAlimentoSedeDeseos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGrupoAlimentoSedeDeseos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarGrupoAlimentoSedeDeseos1ActionPerformed

    private void btnCancelarBusqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarBusqueda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarBusqueda1ActionPerformed

    private void btnCrearNuevoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNuevoGrupoActionPerformed
        FormCrearGrupoAlimento shi = new FormCrearGrupoAlimento();
        shi.setVisible(true);
    }//GEN-LAST:event_btnCrearNuevoGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSedeDeseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSedeDeseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSedeDeseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSedeDeseos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSedeDeseos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarGrupoAlimentoSedeDeseos1;
    private javax.swing.JButton btnBuscarIngredienteSedeDeseos;
    private javax.swing.JButton btnBuscarPlatoSedeDeseos;
    private javax.swing.JButton btnCancelarBusqueda;
    private javax.swing.JButton btnCancelarBusqueda1;
    private javax.swing.JButton btnCancelarBusquedaPlato;
    private javax.swing.JButton btnCrearNuevoGrupo;
    private javax.swing.JButton btnEntradaIngrediente;
    private javax.swing.JButton btnGrupoAlimentos;
    private javax.swing.JButton btnIngredientes1;
    private javax.swing.JButton btnInventarioPlatos;
    private javax.swing.JButton btnSalidaIngrediente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerResumen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JCheckBox jCheckNuevaSedeEstadoActiva;
    public static javax.swing.JCheckBox jCheckNuevaSedeEstadoInactiva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabelCodigoNuevaSede;
    public static javax.swing.JLabel jLabelDireccionNuevaSede;
    public static javax.swing.JLabel jLabelNomAdmNuevaSede;
    private javax.swing.JLabel jLabelNomAdmSede;
    public static javax.swing.JLabel jLabelNombreSede;
    public static javax.swing.JLabel jLabelTelefonoNuevaSede;
    private javax.swing.JLabel jLabelTelefonoSede;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    public static javax.swing.JTextArea txtAreaGruposAlimentosSedeDeseos;
    private javax.swing.JTextArea txtAreaIngredientesNuevaSede;
    private javax.swing.JTextArea txtAreaPlatosNuevaSede;
    private javax.swing.JTextField txtBuscarGrupoAlimentoSedeDeseos1;
    private javax.swing.JTextField txtBuscarIngredienteSedeDeseos;
    private javax.swing.JTextField txtBuscarPlatoSedeDeseos;
    private javax.swing.JTextField txtDia;
    // End of variables declaration//GEN-END:variables
}
