
import java.awt.Toolkit;
import javax.swing.JCheckBox;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Usuario
 */
public class FormCrearSede extends javax.swing.JFrame {

    /**
     * Creates new form FormCrearSede
     */
    public FormCrearSede() {
        initComponents();
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreSede = new javax.swing.JTextField();
        txtCodigoSede = new javax.swing.JTextField();
        txtDireccionSede = new javax.swing.JTextField();
        txtNomAdmSede = new javax.swing.JTextField();
        txtTelefonoSede = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCheckBtnActiva = new javax.swing.JCheckBox();
        jCheckBtnInactiva = new javax.swing.JCheckBox();
        btnCrearSede = new javax.swing.JButton();
        btnCancelarSede = new javax.swing.JButton();
        btnSalirSede = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Nueva Sede");

        jLabelNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel3.setText("Dirección:");

        jLabel5.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel5.setText("Nombre Administrador:");

        jLabel6.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel6.setText("Telefono:");

        txtNombreSede.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreSedeKeyTyped(evt);
            }
        });

        txtNomAdmSede.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomAdmSedeKeyTyped(evt);
            }
        });

        txtTelefonoSede.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoSedeKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel7.setText("Estado:");

        jCheckBtnActiva.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jCheckBtnActiva.setText("Activa");
        jCheckBtnActiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBtnActivaActionPerformed(evt);
            }
        });

        jCheckBtnInactiva.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jCheckBtnInactiva.setText("Inactiva");
        jCheckBtnInactiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBtnInactivaActionPerformed(evt);
            }
        });

        btnCrearSede.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        btnCrearSede.setText("Crear");
        btnCrearSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSedeActionPerformed(evt);
            }
        });

        btnCancelarSede.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        btnCancelarSede.setText("Cancelar");
        btnCancelarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarSedeActionPerformed(evt);
            }
        });

        btnSalirSede.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        btnSalirSede.setText("Salir");
        btnSalirSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirSedeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDireccionSede, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodigoSede, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNomAdmSede, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBtnActiva)
                                    .addComponent(jLabel7)
                                    .addComponent(jCheckBtnInactiva)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCancelarSede, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(btnCrearSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(txtTelefonoSede, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(btnSalirSede, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(txtNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigoSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDireccionSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNomAdmSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBtnActiva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBtnInactiva)
                        .addGap(48, 48, 48)
                        .addComponent(btnCrearSede, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTelefonoSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarSede, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnSalirSede, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(591, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSedeActionPerformed

        if (Utilitaria.validarCadenaVacia(this.txtNombreSede.getText()) && Utilitaria.validarCadenaVacia(this.txtCodigoSede.getText()) && 
            Utilitaria.validarCadenaVacia(this.txtDireccionSede.getText()) && Utilitaria.validarCadenaVacia(this.txtNomAdmSede.getText()) &&
            Utilitaria.validarCadenaVacia(this.txtTelefonoSede.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar el:\n * Nombre\n"
                                                  + " * Código\n * Dirección\n * Nombre Administrador\n"
                                                  + " * Telefono ", "Atención");
            this.txtNombreSede.requestFocus();
        } else if (Utilitaria.validarCadenaVacia(this.txtNombreSede.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar el nombre de la sede", "Atención");
            this.txtNombreSede.requestFocus();

        } else if (Utilitaria.validarCadenaVacia(this.txtCodigoSede.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar el código de la sede", "Atención");
            this.txtCodigoSede.requestFocus();

        } else if (Utilitaria.validarCadenaVacia(this.txtDireccionSede.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar la dirección de la sede", "Atención");
            this.txtDireccionSede.requestFocus();
        } else if (Utilitaria.validarCadenaVacia(this.txtNomAdmSede.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar el nombre del administrador de la sede", "Atención");
            this.txtNomAdmSede.requestFocus();
        } else if (Utilitaria.validarCadenaVacia(this.txtTelefonoSede.getText())) {
            Utilitaria.imprimirEnVentanaInformativa("Debe digitar el telefono de la sede", "Atención");
            this.txtTelefonoSede.requestFocus();
        } else if(jCheckBtnActiva.isSelected() == false && jCheckBtnInactiva.isSelected() == false){
            Utilitaria.imprimirEnVentanaInformativa("Debe marcar si la sede está activa o inactiva", "Atención");
            
        }else {
           

            FormNuevaSede yeah = new FormNuevaSede();

            FormNuevaSede.jLabelNombreSede.setText(this.txtNombreSede.getText());
            FormNuevaSede.jLabelCodigoNuevaSede.setText(this.txtCodigoSede.getText());
            FormNuevaSede.jLabelDireccionNuevaSede.setText(this.txtDireccionSede.getText());
            FormNuevaSede.jLabelNomAdmNuevaSede.setText(this.txtNomAdmSede.getText());
            FormNuevaSede.jLabelTelefonoNuevaSede.setText(this.txtTelefonoSede.getText());
            FormNuevaSede.jCheckNuevaSedeEstadoActiva.setSelected(this.jCheckBtnActiva.isSelected());
            FormNuevaSede.jCheckNuevaSedeEstadoInactiva.setSelected(this.jCheckBtnInactiva.isSelected());
            
            yeah.setVisible(true);

            this.txtNombreSede.setText("");
            this.txtCodigoSede.setText("");
            this.txtDireccionSede.setText("");
            this.txtNomAdmSede.setText("");
            this.txtTelefonoSede.setText("");
        }


    }//GEN-LAST:event_btnCrearSedeActionPerformed

    private void btnSalirSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirSedeActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirSedeActionPerformed

    private void jCheckBtnActivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBtnActivaActionPerformed

        try {
            if (!this.jCheckBtnActiva.getSelectedObjects().equals(null)) {
                this.jCheckBtnInactiva.setSelected(false);
            }
        } catch (Exception ex) {
        }


    }//GEN-LAST:event_jCheckBtnActivaActionPerformed

    private void jCheckBtnInactivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBtnInactivaActionPerformed
        try {
            if (!this.jCheckBtnInactiva.getSelectedObjects().equals(null)) {
                this.jCheckBtnActiva.setSelected(false);
            }
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jCheckBtnInactivaActionPerformed

    private void btnCancelarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarSedeActionPerformed
        this.txtNombreSede.setText("");
        this.txtCodigoSede.setText("");
        this.txtDireccionSede.setText("");
        this.txtNomAdmSede.setText("");
        this.txtTelefonoSede.setText("");
        this.jCheckBtnActiva.setSelected(false);
        this.jCheckBtnInactiva.setSelected(false);
    }//GEN-LAST:event_btnCancelarSedeActionPerformed

    private void txtNombreSedeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreSedeKeyTyped
        char car = evt.getKeyChar();
if((car<'a' || car>'z') && (car<'A' || car>'Z')) evt.consume();
    }//GEN-LAST:event_txtNombreSedeKeyTyped

    private void txtNomAdmSedeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomAdmSedeKeyTyped
        char car = evt.getKeyChar();
if((car<'a' || car>'z') && (car<'A' || car>'Z')) evt.consume();
    }//GEN-LAST:event_txtNomAdmSedeKeyTyped

    private void txtTelefonoSedeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoSedeKeyTyped
         if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoSedeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCrearSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCrearSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCrearSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCrearSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCrearSede().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarSede;
    private javax.swing.JButton btnCrearSede;
    private javax.swing.JButton btnSalirSede;
    private javax.swing.JCheckBox jCheckBtnActiva;
    private javax.swing.JCheckBox jCheckBtnInactiva;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField txtCodigoSede;
    private javax.swing.JTextField txtDireccionSede;
    private javax.swing.JTextField txtNomAdmSede;
    private javax.swing.JTextField txtNombreSede;
    private javax.swing.JTextField txtTelefonoSede;
    // End of variables declaration//GEN-END:variables
}
